### ISSUE TITLE
rt-task (or similar) example export

### ISSUE THREAD

**Issue by vsoch** [openbases/builder-jspsych#1]
hey @jodeleeuw Can you hook me up with a repository that has the tutorial /example for the reaction time task (e.g., this tutorial --> https://www.jspsych.org/tutorials/rt-task/) or similar? I have a feeling you have it somewhere and I'm just missing it. I will include it here in the builder example / template!

**Comment by jodeleeuw** [comment]
It's in the [examples subfolder](https://github.com/jspsych/jsPsych/tree/master/examples) of the main jsPsych repo.

Direct link:
https://github.com/jspsych/jsPsych/blob/master/examples/demo-simple-rt-task.html

**Comment by vsoch** [comment]
Thank you!!  Yeah I wound up finding it there too when I took two seconds to read things. :) closing!
